
---
parser: babel-eslint
parserOptions:
  sourceType: module
  ecmaVersion: 6
  ecmaFeatures:
    modules: true
    experimentalObjectRestSpread: true
extends:
  - prettier
  - plugin:jest/recommended
env:
  es6: true
  jest: true
plugins:
  - prettier
  - jest
rules:
  prettier/prettier:
  - error
  - trailingComma: es5
    singleQuote: true
  jest/no-disabled-tests: warn
  jest/no-focused-tests: error
  jest/no-identical-title: error
  jest/valid-expect: error
  max-nested-callbacks:
  - error
  - 20
