---
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 8
  sourceType: module
extends:
  - airbnb-base
  - plugin:jest/recommended
  - plugin:react/recommended
  - prettier
  - prettier/react
env:
  browser: true
  es6: true
  jest: true
  node: true
  mocha: false
plugins:
  - import
  - jest
  - jsx-a11y
  - prettier
  - react
rules:
  "no-void": 0
  "no-use-before-define":
    - error
    - functions: false
  "no-new-wrappers": 0
settings:
  react:
    version: 'detect'